channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.3
  - aiosignal=1.4.0
  - aiosqlite=0.19.0
  - annotated-doc=0.0.4
  - annotated-types=0.7.0
  - anyio=4.12.1
  - appdirs=1.4.4
  - appnope=0.1.4
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - asttokens=3.0.1
  - async-lru=2.2.0
  - async-timeout=4.0.3
  - attrs=25.4.0
  - aws-c-auth=0.9.3
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.7
  - aws-c-http=0.10.7
  - aws-c-io=0.23.3
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.11.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.35.4
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.1
  - azure-identity-cpp=1.13.2
  - azure-storage-blobs-cpp=12.15.0
  - azure-storage-common-cpp=12.11.0
  - azure-storage-files-datalake-cpp=12.13.0
  - babel=2.18.0
  - backports.zstd=1.3.0
  - banks=2.4.1
  - beautifulsoup4=4.14.3
  - bleach=6.3.0
  - bleach-with-css=6.3.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2026.1.4
  - cffi=1.17.1
  - charset-normalizer=3.4.4
  - click=8.3.1
  - colorama=0.4.6
  - comm=0.2.3
  - cpython=3.13.12
  - cryptography=46.0.5
  - dataclasses-json=0.6.7
  - datasets=4.5.0
  - debugpy=1.8.20
  - decorator=5.2.1
  - defusedxml=0.7.1
  - deprecated=1.2.18
  - dill=0.4.0
  - dirtyjson=1.0.8
  - diskcache=5.6.3
  - distro=1.9.0
  - docstring_parser=0.17.0
  - eval-type-backport=0.2.2
  - eval_type_backport=0.2.2
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - filelock=3.24.3
  - filetype=1.2.0
  - fmt=12.1.0
  - fqdn=1.5.1
  - frozenlist=1.7.0
  - fsspec=2025.10.0
  - gflags=2.2.2
  - git=2.53.0
  - gitdb=4.0.12
  - gitpython=3.1.46
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - google-auth=2.48.0
  - google-genai=1.64.0
  - greenlet=3.3.2
  - griffe=1.15.0
  - h11=0.16.0
  - h2=4.3.0
  - hf-xet=1.2.1
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - httpx-sse=0.4.3
  - huggingface_hub=0.36.0
  - hyperframe=6.1.0
  - icu=73.2
  - idna=3.11
  - importlib-metadata=8.7.0
  - instructor=1.14.5
  - ipykernel=7.2.0
  - ipython=9.10.0
  - ipython_pygments_lexers=1.1.1
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jiter=0.11.1
  - joblib=1.5.3
  - json5=0.13.0
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - jsonschema=4.26.0
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.26.0
  - jupyter-lsp=2.3.0
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.4
  - jupyterlab=4.5.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - krb5=1.21.3
  - langchain=1.2.10
  - langchain-community=0.3.31
  - langchain-core=1.2.14
  - langchain-google-genai=4.2.1
  - langchain-huggingface=1.2.0
  - langchain-openai=1.1.10
  - langchain-text-splitters=0.3.11
  - langgraph=1.0.9
  - langgraph-checkpoint=4.0.0
  - langgraph-prebuilt=1.0.8
  - langgraph-sdk=0.3.8
  - langsmith=0.7.6
  - lark=1.3.1
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250512.1
  - libarrow=22.0.0
  - libarrow-acero=22.0.0
  - libarrow-compute=22.0.0
  - libarrow-dataset=22.0.0
  - libarrow-substrait=22.0.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcrc32c=1.1.2
  - libcurl=8.18.0
  - libcxx=21.1.8
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.4
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libiconv=1.18
  - libintl=0.25.1
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - libmpdec=4.0.0
  - libnghttp2=1.67.0
  - libopenblas=0.3.30
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libparquet=22.0.0
  - libpng=1.6.55
  - libprotobuf=6.31.1
  - libre2-11=2025.11.05
  - libsodium=1.0.20
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libtiff=4.7.0
  - libtorch=2.10.0
  - libutf8proc=2.11.3
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llama-cloud=0.1.35
  - llama-cloud-services=0.6.54
  - llama-index=0.14.15
  - llama-index-cli=0.5.3
  - llama-index-core=0.14.15
  - llama-index-embeddings-openai=0.5.1
  - llama-index-indices-managed-llama-cloud=0.9.4
  - llama-index-instrumentation=0.4.2
  - llama-index-llms-openai=0.6.19
  - llama-index-readers-file=0.5.6
  - llama-index-readers-llama-parse=0.5.1
  - llama-index-workflows=2.14.2
  - llama-parse=0.6.54
  - llamaindex-py-client=0.1.19
  - llvm-openmp=21.1.8
  - lz4-c=1.10.0
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - marshmallow=3.26.1
  - matplotlib-inline=0.2.1
  - mdurl=0.1.2
  - mistune=3.2.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.7.1
  - multiprocess=0.70.18
  - mypy_extensions=1.1.0
  - nbclient=0.10.4
  - nbconvert-core=7.17.0
  - nbformat=5.10.4
  - ncurses=6.5
  - neo4j-python-driver=6.1.0
  - nest-asyncio=1.6.0
  - networkx=3.6.1
  - nlohmann_json=3.12.0
  - nltk=3.9.2
  - nomkl=1.0
  - notebook-shim=0.2.4
  - numpy=2.4.2
  - openai=2.21.0
  - openjpeg=2.5.3
  - openssl=3.6.1
  - optree=0.18.0
  - orc=2.2.2
  - orjson=3.11.7
  - ormsgpack=1.12.2
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandocfilters=1.5.0
  - parso=0.8.6
  - pcre2=10.47
  - perl=5.32.1
  - pexpect=4.9.0
  - pillow=11.3.0
  - pip=26.0.1
  - platformdirs=4.9.2
  - prometheus-cpp=1.3.0
  - prometheus_client=0.24.1
  - prompt-toolkit=3.0.52
  - propcache=0.3.1
  - psutil=7.2.2
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=22.0.0
  - pyarrow-core=22.0.0
  - pyasn1=0.6.2
  - pyasn1-modules=0.4.2
  - pybind11=3.0.2
  - pybind11-abi=11
  - pybind11-global=3.0.2
  - pycparser=2.22
  - pydantic=2.12.5
  - pydantic-core=2.41.5
  - pydantic-settings=2.13.1
  - pygments=2.19.2
  - pyobjc-core=11.0
  - pyobjc-framework-cocoa=11.0
  - pyopenssl=25.3.0
  - pypdf=6.7.2
  - pysbd=0.3.4
  - pysocks=1.7.1
  - python=3.13.11
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.2.1
  - python-fastjsonschema=2.21.2
  - python-gil=3.13.12
  - python-json-logger=2.0.7
  - python-tzdata=2025.3
  - python-xxhash=3.6.0
  - python_abi=3.13
  - pytorch=2.10.0
  - pytz=2025.2
  - pyu2f=0.1.5
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - ragas=0.4.3
  - re2=2025.11.05
  - readline=8.3
  - referencing=0.37.0
  - regex=2026.2.19
  - requests=2.32.5
  - requests-toolbelt=1.0.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rich=14.3.3
  - rpds-py=0.30.0
  - rsa=4.9.1
  - safetensors=0.7.0
  - scikit-learn=1.8.0
  - scikit-network=0.33.5
  - scipy=1.17.0
  - send2trash=2.1.0
  - sentence-transformers=5.2.3
  - setuptools=80.10.2
  - shellingham=1.5.4
  - six=1.17.0
  - sleef=3.9.0
  - smmap=5.0.2
  - snappy=1.2.2
  - sniffio=1.3.1
  - soupsieve=2.8.3
  - sqlalchemy=2.0.46
  - sqlite=3.51.1
  - stack_data=0.6.3
  - striprtf=0.0.26
  - sympy=1.14.0
  - tenacity=9.1.4
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tiktoken=0.12.0
  - tinycss2=1.4.0
  - tinytag=2.2.0
  - tk=8.6.15
  - tokenizers=0.22.2
  - tomli=2.4.0
  - tornado=6.5.4
  - tqdm=4.67.3
  - traitlets=5.14.3
  - transformers=4.57.6
  - typer=0.24.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - typing_inspect=0.9.0
  - typing_utils=0.1.0
  - tzdata=2025c
  - uri-template=1.3.0
  - urllib3=2.6.3
  - uuid-utils=0.14.1
  - wcwidth=0.6.0
  - webcolors=25.10.0
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - websockets=15.0.1
  - wheel=0.46.3
  - wrapt=1.17.3
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xxhash=0.8.3
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.22.0
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - pymupdf==1.27.1
